"""
backend/reports/pdf_generator.py

Professional Authority-Grade Audit PDF Generation Engine for TERRANODE.
Generates comprehensive 11-section printable government audit reports using ReportLab.
Adheres strictly to active_dataset_id isolation and uses real data.
"""

from __future__ import annotations

import io
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    HRFlowable,
    KeepTogether,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from backend.reports.summary_service import compute_report_summary


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to dynamically compute and print 'Page X of Y' along with running header.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica-Bold", 8)
        self.setFillColor(colors.HexColor("#475569"))

        # Running header on pages after the first
        if self._pageNumber > 1:
            self.drawString(54, 11 * inch - 36, "TERRANODE · RECONCILIATION AUDIT REPORT")
            self.setFont("Helvetica", 8)
            self.drawRightString(8.5 * inch - 54, 11 * inch - 36, "Official Authority Verification Document")
            self.setStrokeColor(colors.HexColor("#CBD5E1"))
            self.setLineWidth(0.5)
            self.line(54, 11 * inch - 42, 8.5 * inch - 54, 11 * inch - 42)

        # Running footer on every page
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))
        self.drawString(54, 36, "CONFIDENTIAL & AUTHORITATIVE · Generated by TERRANODE Autonomous Reconciliation Core")
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(8.5 * inch - 54, 36, page_str)
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(54, 48, 8.5 * inch - 54, 48)

        self.restoreState()


def generate_audit_pdf(dataset_id: Optional[str] = None) -> bytes:
    """
    Generates a complete, multi-page professional PDF report for the active dataset.
    Returns the binary PDF bytes.
    """
    data = compute_report_summary(dataset_id)

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    c_navy = colors.HexColor("#0F172A")
    c_dark = colors.HexColor("#1E293B")
    c_muted = colors.HexColor("#64748B")
    c_green = colors.HexColor("#15803D")
    c_amber = colors.HexColor("#B45309")
    c_red = colors.HexColor("#B91C1C")

    title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        textColor=c_navy,
    )
    subtitle_style = ParagraphStyle(
        "DocSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=c_muted,
    )
    h1_style = ParagraphStyle(
        "H1Section",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=16,
        textColor=c_navy,
        spaceBefore=14,
        spaceAfter=6,
    )
    body_style = ParagraphStyle(
        "BodyDark",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=13,
        textColor=c_dark,
    )
    bold_body_style = ParagraphStyle(
        "BoldBodyDark",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=13,
        textColor=c_dark,
    )
    th_style = ParagraphStyle(
        "TableHeader",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=8.5,
        leading=11,
        textColor=colors.white,
    )
    td_style = ParagraphStyle(
        "TableCell",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8,
        leading=11,
        textColor=c_dark,
    )
    td_bold = ParagraphStyle(
        "TableCellBold",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=8,
        leading=11,
        textColor=c_dark,
    )

    story = []

    # -------------------------------------------------------------------------
    # COVER / HEADER BANNER
    # -------------------------------------------------------------------------
    now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    
    header_table_data = [
        [
            Paragraph("<b>TERRANODE</b>", ParagraphStyle("Brand", fontName="Helvetica-Bold", fontSize=10, textColor=colors.HexColor("#D97706"))),
            Paragraph(f"REPORT GENERATED: <b>{now_str}</b>", ParagraphStyle("GenDate", fontName="Helvetica", fontSize=8, alignment=2, textColor=c_muted)),
        ],
        [
            Paragraph("RECONCILIATION AUDIT REPORT", title_style),
            Paragraph(f"STATUS: <font color='#15803D'><b>{data['status']}</b></font>", ParagraphStyle("StatBadge", fontName="Helvetica-Bold", fontSize=11, alignment=2)),
        ],
        [
            Paragraph("Evidence-backed verification of the active land dataset", subtitle_style),
            Paragraph(f"AREA: <b>{data['city']} — {data['aoi']}</b>", ParagraphStyle("AreaHead", fontName="Helvetica", fontSize=9, alignment=2, textColor=c_dark)),
        ],
    ]
    header_table = Table(header_table_data, colWidths=[330, 174])
    header_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
        ("TOPPADDING", (0, 0), (-1, -1), 2),
    ]))
    story.append(header_table)
    story.append(Spacer(1, 8))
    story.append(HRFlowable(width="100%", thickness=1.5, color=c_navy, spaceBefore=4, spaceAfter=12))

    # -------------------------------------------------------------------------
    # SECTION 1 — DATASET INFORMATION
    # -------------------------------------------------------------------------
    story.append(Paragraph("1. DATASET INFORMATION", h1_style))
    ds_info_rows = [
        [
            Paragraph("<b>Dataset Name:</b>", body_style), Paragraph(str(data["name"]), body_style),
            Paragraph("<b>Dataset ID:</b>", body_style), Paragraph(str(data["dataset_id"]), body_style),
        ],
        [
            Paragraph("<b>City / Urban Area:</b>", body_style), Paragraph(f"{data['city']} ({data['aoi']})", body_style),
            Paragraph("<b>Dataset Version:</b>", body_style), Paragraph(str(data["version"]), body_style),
        ],
        [
            Paragraph("<b>Processing Date:</b>", body_style), Paragraph(str(data["upload_date"]), body_style),
            Paragraph("<b>Authoritative CRS:</b>", body_style), Paragraph(str(data["crs"]), body_style),
        ],
        [
            Paragraph("<b>Total Entities:</b>", body_style), Paragraph(f"<b>{data['reconciliation_status']['total']} Parcels</b>", bold_body_style),
            Paragraph("<b>Verification State:</b>", body_style), Paragraph(str(data["status"]), bold_body_style),
        ],
    ]
    t_ds = Table(ds_info_rows, colWidths=[110, 142, 110, 142])
    t_ds.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ("PADDING", (0, 0), (-1, -1), 5),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(t_ds)
    story.append(Spacer(1, 10))

    # -------------------------------------------------------------------------
    # SECTION 2 — RECONCILIATION SUMMARY
    # -------------------------------------------------------------------------
    story.append(Paragraph("2. RECONCILIATION SUMMARY", h1_style))
    rec = data["reconciliation_status"]
    rec_summary_data = [
        [
            Paragraph("METRIC CATEGORY", th_style),
            Paragraph("PARCEL COUNT", th_style),
            Paragraph("DISTRIBUTION (%)", th_style),
            Paragraph("AUDIT STATUS", th_style),
        ],
        [
            Paragraph("Verified (Auto-Harmonized)", td_bold),
            Paragraph(f"<b>{rec['verified']}</b>", td_style),
            Paragraph(f"{rec['verified_percentage']}%", td_style),
            Paragraph("<font color='#15803D'><b>VERIFIED · READY</b></font>", td_style),
        ],
        [
            Paragraph("Surveyor Review Required", td_bold),
            Paragraph(f"<b>{rec['review']}</b>", td_style),
            Paragraph(f"{rec['review_percentage']}%", td_style),
            Paragraph("<font color='#B45309'><b>REVIEW RECOMMENDED</b></font>", td_style),
        ],
        [
            Paragraph("Spatial Conflict Detected", td_bold),
            Paragraph(f"<b>{rec['conflict']}</b>", td_style),
            Paragraph(f"{rec['conflict_percentage']}%", td_style),
            Paragraph("<font color='#B91C1C'><b>CONFLICT QUEUED</b></font>", td_style),
        ],
        [
            Paragraph("Total Land Parcels Analyzed", td_bold),
            Paragraph(f"<b>{rec['total']}</b>", td_bold),
            Paragraph("100.0%", td_bold),
            Paragraph(f"Avg Confidence: <b>{rec['overall_confidence']}%</b>", td_bold),
        ],
    ]
    t_rec = Table(rec_summary_data, colWidths=[184, 100, 100, 120])
    t_rec.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), c_navy),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -2), [colors.white, colors.HexColor("#F8FAFC")]),
        ("BACKGROUND", (0, -1), (-1, -1), colors.HexColor("#F1F5F9")),
        ("PADDING", (0, 0), (-1, -1), 5),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(t_rec)
    story.append(Spacer(1, 10))

    # -------------------------------------------------------------------------
    # SECTION 3 — SOURCE EVIDENCE
    # -------------------------------------------------------------------------
    story.append(Paragraph("3. SOURCE EVIDENCE", h1_style))
    src_data = [
        [
            Paragraph("AUTHORITATIVE DATA SOURCE", th_style),
            Paragraph("LAYER TYPE", th_style),
            Paragraph("PARTICIPATING PARCELS", th_style),
            Paragraph("COVERAGE", th_style),
            Paragraph("STATUS", th_style),
        ]
    ]
    for s in data["source_contribution"]:
        src_data.append([
            Paragraph(s["source_name"], td_bold),
            Paragraph(s["source_key"].upper(), td_style),
            Paragraph(f"{s['count']} parcels", td_style),
            Paragraph(f"{s['coverage_percentage']}%", td_style),
            Paragraph("<font color='#15803D'><b>VERIFIED</b></font>", td_style),
        ])
    t_src = Table(src_data, colWidths=[194, 70, 110, 60, 70])
    t_src.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), c_navy),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
        ("PADDING", (0, 0), (-1, -1), 4.5),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(t_src)
    story.append(Spacer(1, 10))

    # -------------------------------------------------------------------------
    # SECTION 4 — SPATIAL QUALITY
    # -------------------------------------------------------------------------
    story.append(Paragraph("4. SPATIAL QUALITY BENCHMARKS", h1_style))
    sq = data["spatial_quality"]
    sq_data = [
        [
            Paragraph("QUALITY MEASURE", th_style),
            Paragraph("MEASURED VALUE", th_style),
            Paragraph("AUTHORITATIVE THRESHOLD", th_style),
            Paragraph("AUDIT STATUS", th_style),
            Paragraph("EVALUATION PURPOSE", th_style),
        ]
    ]
    for key in ["iou", "boundary_agreement", "ground_truth_agreement", "verification_confidence"]:
        item = sq[key]
        sq_data.append([
            Paragraph(f"<b>{item['name']}</b>", td_style),
            Paragraph(f"<b>{item['percentage']}%</b> ({item['value']})", td_style),
            Paragraph(f"&ge; {item['threshold_percentage']}%", td_style),
            Paragraph(f"<font color='#15803D'><b>{item['status']}</b></font>", td_style),
            Paragraph(item["tooltip"], td_style),
        ])
    t_sq = Table(sq_data, colWidths=[120, 85, 95, 65, 139])
    t_sq.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), c_navy),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
        ("PADDING", (0, 0), (-1, -1), 4.5),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(t_sq)
    story.append(Spacer(1, 10))

    # -------------------------------------------------------------------------
    # SECTION 5 — CONFLICT SUMMARY
    # -------------------------------------------------------------------------
    story.append(Paragraph("5. SPATIAL CONFLICT SUMMARY", h1_style))
    cb = data["spatial_conflict_breakdown"]
    if cb:
        cb_data = [
            [
                Paragraph("CONFLICT CLASSIFICATION", th_style),
                Paragraph("INCIDENCE COUNT", th_style),
                Paragraph("DISCREPANCY DESCRIPTION", th_style),
                Paragraph("RESOLUTION STATUS", th_style),
            ]
        ]
        for c in cb:
            cb_data.append([
                Paragraph(f"<b>{c['conflict_type']}</b>", td_style),
                Paragraph(f"<b>{c['count']}</b>", td_style),
                Paragraph(c["description"], td_style),
                Paragraph("<font color='#B91C1C'><b>PENDING REVIEW</b></font>", td_style),
            ])
        t_cb = Table(cb_data, colWidths=[140, 75, 209, 80])
        t_cb.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), c_navy),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
            ("PADDING", (0, 0), (-1, -1), 4.5),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]))
        story.append(t_cb)
    else:
        story.append(Paragraph("<i>No spatial conflicts detected in active dataset. All boundaries meet consensus standards.</i>", body_style))
    story.append(Spacer(1, 10))

    # -------------------------------------------------------------------------
    # SECTION 6 — PARCEL CONFLICT DETAILS (CONFLICT LEDGER TABLE)
    # -------------------------------------------------------------------------
    story.append(KeepTogether([
        Paragraph("6. PARCEL RECONCILIATION LEDGER (ISSUES REQUIRING INSPECTION)", h1_style),
        Paragraph("The following parcels exhibit coordinate boundary drift, lower consensus overlap, or multi-source discrepancies requiring cadastral surveyor review:", subtitle_style),
        Spacer(1, 4),
    ]))

    attention_parcels = [item for item in data["conflict_ledger"] if item["status"] in ("conflict", "review")]
    if not attention_parcels:
        # Fallback to first 8 parcels if all verified
        attention_parcels = data["conflict_ledger"][:8]

    p_data = [
        [
            Paragraph("PARCEL ID", th_style),
            Paragraph("SURVEY NO", th_style),
            Paragraph("CONFLICT TYPE", th_style),
            Paragraph("SOURCES", th_style),
            Paragraph("DRIFT", th_style),
            Paragraph("IOU", th_style),
            Paragraph("CONF", th_style),
            Paragraph("STATUS", th_style),
        ]
    ]
    for p in attention_parcels[:15]:  # Show top 15 on report
        stat_color = "#B91C1C" if p["status"] == "conflict" else ("#B45309" if p["status"] == "review" else "#15803D")
        p_data.append([
            Paragraph(p["parcel_id"], td_bold),
            Paragraph(p["survey_number"], td_style),
            Paragraph(p["conflict_type"], td_style),
            Paragraph(f"{p['sources_count']} Sources", td_style),
            Paragraph(f"{p['boundary_drift_m']}m", td_style),
            Paragraph(f"{p['iou']:.2f}", td_style),
            Paragraph(f"{p['confidence_pct']:.0f}%", td_style),
            Paragraph(f"<font color='{stat_color}'><b>{p['status'].upper()}</b></font>", td_style),
        ])

    t_p = Table(p_data, colWidths=[70, 75, 110, 65, 45, 40, 40, 59])
    t_p.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), c_navy),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
        ("PADDING", (0, 0), (-1, -1), 4),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(t_p)
    story.append(Spacer(1, 10))

    # -------------------------------------------------------------------------
    # SECTION 7 — EVIDENCE COVERAGE
    # -------------------------------------------------------------------------
    story.append(KeepTogether([
        Paragraph("7. EVIDENCE COVERAGE & AUDIT PILLARS", h1_style),
    ]))
    ec_data = [
        [
            Paragraph("EVIDENCE DOMAIN", th_style),
            Paragraph("COVERAGE STATE", th_style),
            Paragraph("PROVENANCE & METHODOLOGY NOTE", th_style),
        ]
    ]
    for ec in data["evidence_coverage"]:
        st_color = "#15803D" if ec["status"] == "Complete" else ("#B45309" if ec["status"] == "Partial" else "#64748B")
        ec_data.append([
            Paragraph(f"<b>{ec['category']}</b>", td_style),
            Paragraph(f"<font color='{st_color}'><b>{ec['status'].upper()}</b></font>", td_style),
            Paragraph(ec["note"], td_style),
        ])
    t_ec = Table(ec_data, colWidths=[150, 95, 259])
    t_ec.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), c_navy),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
        ("PADDING", (0, 0), (-1, -1), 4.5),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(t_ec)
    story.append(Spacer(1, 10))

    # -------------------------------------------------------------------------
    # SECTION 8 — RECONCILIATION PIPELINE
    # -------------------------------------------------------------------------
    story.append(Paragraph("8. RECONCILIATION PIPELINE PROGRESSION", h1_style))
    pipe_data = [
        [
            Paragraph("STAGE", th_style),
            Paragraph("PIPELINE OPERATIONAL STAGE", th_style),
            Paragraph("PROCESSING STATE", th_style),
            Paragraph("STAGE DESCRIPTION", th_style),
        ]
    ]
    for ps in data["pipeline_stages"]:
        st_color = "#15803D" if ps["status"] == "Completed" else ("#B45309" if ps["status"] == "Review" else "#64748B")
        pipe_data.append([
            Paragraph(f"0{ps['order']}", td_bold),
            Paragraph(f"<b>{ps['stage']}</b> ({ps['label']})", td_style),
            Paragraph(f"<font color='{st_color}'><b>{ps['status'].upper()}</b></font>", td_style),
            Paragraph(ps["description"], td_style),
        ])
    t_pipe = Table(pipe_data, colWidths=[35, 145, 95, 229])
    t_pipe.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), c_navy),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
        ("PADDING", (0, 0), (-1, -1), 4),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(t_pipe)
    story.append(Spacer(1, 10))

    # -------------------------------------------------------------------------
    # SECTION 9 — AUDIT HISTORY TIMELINE
    # -------------------------------------------------------------------------
    story.append(Paragraph("9. AUDIT HISTORY & LIFECYCLE EVENTS", h1_style))
    ah_data = [
        [
            Paragraph("EVENT TIMESTAMP", th_style),
            Paragraph("ACTION / LIFECYCLE EVENT", th_style),
            Paragraph("ACTOR / SUBSYSTEM", th_style),
            Paragraph("STATUS", th_style),
        ]
    ]
    for ah in data["audit_history"]:
        ah_data.append([
            Paragraph(ah["timestamp"], td_style),
            Paragraph(ah["event"], td_bold),
            Paragraph(ah.get("actor", "Core Engine"), td_style),
            Paragraph("<font color='#15803D'><b>" + ah["status"].upper() + "</b></font>", td_style),
        ])
    t_ah = Table(ah_data, colWidths=[120, 204, 110, 70])
    t_ah.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), c_navy),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
        ("PADDING", (0, 0), (-1, -1), 4),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(t_ah)
    story.append(Spacer(1, 10))

    # -------------------------------------------------------------------------
    # SECTION 10 — CURRENT DATASET STATUS & DISCLAIMER
    # -------------------------------------------------------------------------
    story.append(KeepTogether([
        Paragraph("10. CURRENT DATASET STATUS & SPATIAL VERIFICATION STATEMENT", h1_style),
        Paragraph(
            f"The active dataset <b>{data['name']}</b> ({data['city']} — {data['aoi']}) currently holds an audit status of "
            f"<b>{data['status']}</b>. A total of {data['reconciliation_status']['verified']} of {data['reconciliation_status']['total']} parcels "
            f"({data['reconciliation_status']['verified_percentage']}%) meet the strict dual-threshold criteria "
            f"(IoU &ge; 0.85 and Centroid Drift &lt; 2.0 meters) and are certified for authoritative land record workflows. "
            f"The remaining {data['reconciliation_status']['review'] + data['reconciliation_status']['conflict']} parcels "
            f"have been formally queued in the Conflict Ledger for surveyor inspection.",
            body_style
        ),
        Spacer(1, 4),
        Paragraph(
            "<b>STATUTORY NOTICE:</b> This document provides spatial geometry reconciliation, multi-source sensor agreement, "
            "and technical evidentiary verification only. It does not constitute a final judicial determination of legal title or ownership. "
            "Administrative registration of final boundaries must follow statutory procedures stipulated under the relevant State Land Revenue Act.",
            ParagraphStyle("Disclaimer", parent=body_style, fontSize=7.5, leading=10, textColor=c_muted)
        ),
        Spacer(1, 8),
    ]))

    # -------------------------------------------------------------------------
    # SECTION 11 — DATA SOURCES & METHODOLOGY
    # -------------------------------------------------------------------------
    story.append(KeepTogether([
        Paragraph("11. DATA SOURCES & RECONCILIATION METHODOLOGY", h1_style),
        Paragraph(
            "<b>Methodological Architecture:</b> Spatial reconciliation in TERRANODE employs an 8-signal scoring matrix "
            "(combining Intersection-over-Union, centroid offset, area delta, perimeter agreement, shape similarity, and bounding-box overlap) "
            "indexed with Shapely STRtrees. Coordinate references are validated in native projected UTM metric systems "
            "prior to comparison, eliminating angular degree distortion. Ground-truth verification uses Survey of India CORS GNSS "
            "stations as authoritative reference coordinates.",
            ParagraphStyle("Method", parent=body_style, fontSize=8, leading=11, textColor=c_dark)
        ),
    ]))

    doc.build(story, canvasmaker=NumberedCanvas)
    buffer.seek(0)
    return buffer.getvalue()
